# Generated by Django 3.0 on 2021-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Expyear',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='creditcardnumber',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='cvv',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='expmonth',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='nameoncard',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
    ]
