# Generated by Django 3.0 on 2021-05-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210506_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='pin',
            field=models.IntegerField(null='True'),
        ),
    ]
