# Generated by Django 3.0 on 2021-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20210511_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Shopkeeper'), (3, 'Anonymous')], default=3),
        ),
    ]
