# Generated by Django 3.0 on 2021-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_auto_20210527_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quant',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
