# Generated by Django 3.0 on 2021-05-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20210508_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
        ),
    ]
