# Generated by Django 3.0 on 2021-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20210511_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
