from django.urls import path
from App import views
from django.contrib.auth import views as ay

urlpatterns = [
	path('',views.home,name='hm'),
	path('lg/',ay.LoginView.as_view(template_name="html/login.html"),name="lgo"),
	path('reg/',views.register,name="rg"),
	path('abt/',views.about,name='at'),
	path('lgout/',ay.LogoutView.as_view(template_name='html/logout.html'),name="log"),
	path('pf/',views.profile,name='prf'),
	# path('hcft/',views.hc,name="hct"),
	path('ch/',views.cgf,name="cg"),
	path('sd/',views.showdata,name="shd"),
	path('del/<int:st>/',views.delete,name="del"),
	path('upd/<int:up>/',views.update,name="upit"),
    path('sr/<int:id>/',views.women,name="sr"),
    path('cst/',views.custom,name="cstm"),
    path('adc/<int:id>/',views.cart,name="act"),
    path('crtcnt/',views.cartcount,name="cnt"),
    path('cartdata/',views.cartdetails,name="cartdetails"),
    path('remove/<int:id>/',views.remove,name="rem"),
    path('placeorder/',views.placeorder,name="porder"),
    path('pdf/',views.pdf,name="pdf"),
    path('checkout/',views.checkout,name="checkout"),
    path('msg/',views.msg,name="msg"),
    path('myorders/',views.myorders,name="myorders"),
    path('msg1/',views.msg1,name="msg1"),
    path('rst/',ay.PasswordResetView.as_view(template_name="html/resetpassword.html"),name="rt"),
    path('rst_done/',ay.PasswordResetDoneView.as_view(template_name="html/resetpassworddone.html"),name="password_reset_done"),
    path('rst_cf/<uidb64>/<token>/',ay.PasswordResetConfirmView.as_view(template_name="html/resetpasswordconfirm.html"),name="password_reset_confirm"),
    path('rst_cmplt/',ay.PasswordResetCompleteView.as_view(template_name="html/resetpwdcomplete.html"),name="password_reset_complete"),
    path('addp/',views.addproduct,name='addpro'),
    path('upf/',views.updateprofile,name='updatepf'),
    path('per/',views.permissions,name='perm'),
    path('rlrq',views.rolreq,name='rr'),
    path('gvp/<int:k>/',views.giveper,name='gvpr'),
    path('prodc/<int:si>/',views.prodcust,name="prodc"),
    path('ordcancel/<int:si>/',views.ordercancel,name="ordcancel"),
    path('sort/<int:id>/',views.sort,name="sort"),
    path('search/',views.search,name="search"),
    path('shop/',views.shop,name="shop"),
    ]
