# Generated by Django 3.0 on 2021-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210508_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Shopkeeper'), (3, 'Anonymous')], default=2),
        ),
    ]
