# Generated by Django 3.0 on 2021-05-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolerest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('roletype', models.CharField(choices=[(1, 'customer'), (2, 'anonymous')], max_length=10)),
                ('is_checked', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Customerdetails',
        ),
        migrations.AddField(
            model_name='user',
            name='Expyear',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='creditcardnumber',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='expmonth',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='nameoncard',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=40, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='customise',
            name='phno',
            field=models.CharField(max_length=20, null='True'),
        ),
        migrations.DeleteModel(
            name='HandiCrafts',
        ),
        migrations.AddField(
            model_name='rolerest',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
