# Generated by Django 3.0 on 2021-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20210516_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quant',
            field=models.IntegerField(default=0),
        ),
    ]
