# Generated by Django 3.0 on 2021-05-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20210517_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Product'),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(choices=[('product quality issues', 'product quality issues'), ('I want to change address/phone number', 'I want to change address/phone number'), ('I have purchased product somewhere else', 'I have purchased product somewhere else'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
