# Generated by Django 3.0 on 2021-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210429_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='im',
            field=models.ImageField(default='home3.jpg', upload_to=''),
        ),
    ]
