# Generated by Django 3.0 on 2021-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210506_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='pname',
            field=models.CharField(max_length=300),
        ),
    ]
