# Generated by Django 3.0 on 2021-05-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210507_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
    ]
