# Generated by Django 3.0 on 2021-05-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_remove_product_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.IntegerField(null=True),
        ),
    ]
