# Generated by Django 3.0 on 2021-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_product_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cancel',
        ),
        migrations.AddField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(choices=[('1', 'product quality issues'), ('2', 'I want to change address/phone number'), ('3', 'I have purchased product somewhere else'), ('4', 'others')], max_length=20, null=True),
        ),
    ]
