# Generated by Django 3.0 on 2021-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20210518_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Shopkeeper'), (3, 'Anonymous')], default=1),
        ),
    ]
