# Generated by Django 3.0 on 2021-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_myorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
