# Generated by Django 3.0 on 2021-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210506_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='phno',
            field=models.IntegerField(null='True'),
        ),
    ]
