# Generated by Django 3.0 on 2021-05-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_myorders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
        ),
    ]
