# Generated by Django 3.0 on 2021-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20210511_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerest',
            name='roletype',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'anonymous')]),
        ),
    ]
